# Generated by Django 4.2.9 on 2024-01-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loc',
            field=models.CharField(default='bangladesh', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='default-avatar-profile-icon-vector-260nw-1725655669.webp', upload_to='profile_image'),
        ),
    ]
