# Generated by Django 4.2.9 on 2024-01-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0008_alter_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='tryTheenv')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
