# Generated by Django 4.2.9 on 2024-01-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0010_like_post_alter_img_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Follower', models.CharField(max_length=25)),
                ('user', models.CharField(max_length=25)),
            ],
        ),
    ]
